# Generated by Django 6.0.2 on 2026-06-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.category",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
