# Generated by Django 6.0.2 on 2026-06-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_budget_category_budget_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="transactions.category"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="month",
            field=models.IntegerField(),
        ),
    ]
